services:
  db:
    image: postgres:14
    container_name: warehouse_app_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      timeout: 5s
      interval: 10s
      retries: 5
    restart: unless-stopped

  ktor-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: warehouse_app_backend
    env_file:
      - .env 
    ports:
      - "8080:8080"
    environment:
      KTOR_CONFIG: "application-docker.yaml"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PRIVATE_KEY_PATH: ${PRIVATE_KEY_PATH}
      PUBLIC_KEY_PATH: ${PUBLIC_KEY_PATH}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped 


volumes:
  postgres_data: